### PR TITLE
Issue #76, replaced deprecated MappingJacksonHttpMessageConverter

### PR DESCRIPTION
**Pull request by dynamind**
Tested for Grails 2.3.5 - 2.5.0

### CODE REVIEW

**Comment by bluesliverx** [comment]
The second travis pull request check is unecessary.  Can you remove this commit from the PR and I'll do a separate commit to fix the issue?

**Comment by dynamind** [comment]
You mean like this?

**Comment by bluesliverx** [comment]
Exactly, thanks!

**Comment by bluesliverx** [comment]
Actually, I'm looking at it on my phone, but the Travis build failed due to invalid syntax. It looks like you inserted a period at the beginning of each line in the indentation.

**Comment by dynamind** [comment]
Yes, sorry. I think I fixed it :-)

**Comment by bluesliverx** [comment]
Thanks!

**Pull request merged**
